mode: rule
mixed-port: 7897
allow-lan: true
bind-address: "*"
log-level: info
ipv6: false
external-controller: 127.0.0.1:9097
secret: "CHANGE_ME_CONTROLLER_SECRET"
unified-delay: false

tun:
  enable: true
  stack: gvisor
  auto-route: true
  auto-detect-interface: true
  strict-route: false
  mtu: 1500
  device: Mihomo
  dns-hijack:
    - any:53
    - tcp://any:53
  route-exclude-address:
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12

external-controller-cors:
  allow-private-network: true
  allow-origins:
    - tauri://localhost
    - http://tauri.localhost
    - https://yacd.metacubex.one
    - https://metacubex.github.io

dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  listen: :53
  default-nameserver:
    - 223.6.6.6
    - 119.29.29.29
  direct-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  direct-nameserver-follow-policy: false
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "*.arpa"
    - time.*.com
    - ntp.*.com
    - +.market.xiaomi.com
    - localhost.ptlogin2.qq.com
    - "*.msftncsi.com"
    - www.msftconnecttest.com
  fallback: []
  fallback-filter:
    domain:
      - +.google.com
      - +.facebook.com
      - +.youtube.com
    geoip: true
    geoip-code: CN
    ipcidr:
      - 240.0.0.0/4
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  prefer-h3: false
  respect-rules: false
  use-hosts: false
  use-system-hosts: false

prepend-rules:
  - IP-CIDR,198.18.0.0/16,🚀 节点选择,no-resolve
  - IP-CIDR,192.168.0.0/16,DIRECT,no-resolve
  - IP-CIDR,10.0.0.0/8,DIRECT,no-resolve
  - IP-CIDR,172.16.0.0/12,DIRECT,no-resolve

profile:
  store-selected: true
